export default {
  CONTACTS_VALUE_UPDATED: 'CONTACTS_VALUE_UPDATED',
  CONTACTS_ROW_CLICKED: 'CONTACTS_ROW_CLICKED',
  CONTACTS_NEW: 'CONTACTS_NEW',
  CONTACTS_ROW_DELETE: 'CONTACT_ROW_DELETE',
  CONTACTS_SAVE_CONTACT: 'CONTACTS_SAVE_CONTACT',
  CONTACTS_UPDATE_TAB_CONTACT: 'CONTACTS_UPDATE_TAB_CONTACT',
}
